import '../models/category.dart';

/// Predefined category definitions.
final List<FinanceCategory> defaultPredefinedCategories = [
  // Expenses
  FinanceCategory(
    id: 'cat_food',
    name: 'Food & Dining',
    type: CategoryType.expense,
    iconName: 'restaurant',
    colorHex: '#FF5722',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_groceries',
    name: 'Groceries',
    type: CategoryType.expense,
    iconName: 'shopping_cart',
    colorHex: '#4CAF50',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_housing',
    name: 'Housing & Rent',
    type: CategoryType.expense,
    iconName: 'home',
    colorHex: '#3F51B5',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_utilities',
    name: 'Utilities & Bills',
    type: CategoryType.expense,
    iconName: 'bolt',
    colorHex: '#FFB300',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_transport',
    name: 'Transportation',
    type: CategoryType.expense,
    iconName: 'directions_car',
    colorHex: '#00BCD4',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_shopping',
    name: 'Shopping',
    type: CategoryType.expense,
    iconName: 'shopping_bag',
    colorHex: '#E91E63',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_health',
    name: 'Health & Medical',
    type: CategoryType.expense,
    iconName: 'medical_services',
    colorHex: '#F44336',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_entertainment',
    name: 'Entertainment',
    type: CategoryType.expense,
    iconName: 'movie',
    colorHex: '#9C27B0',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_education',
    name: 'Education',
    type: CategoryType.expense,
    iconName: 'school',
    colorHex: '#2196F3',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_travel',
    name: 'Travel',
    type: CategoryType.expense,
    iconName: 'flight',
    colorHex: '#009688',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_subscriptions',
    name: 'Subscriptions',
    type: CategoryType.expense,
    iconName: 'subscriptions',
    colorHex: '#673AB7',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_personal',
    name: 'Personal Care',
    type: CategoryType.expense,
    iconName: 'spa',
    colorHex: '#8BC34A',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_transfer',
    name: 'Transfer',
    type: CategoryType.expense,
    iconName: 'swap_horiz',
    colorHex: '#607D8B',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_adjustment',
    name: 'Reconciliation Adjustment',
    type: CategoryType.expense,
    iconName: 'tune',
    colorHex: '#795548',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_misc_expense',
    name: 'Miscellaneous',
    type: CategoryType.expense,
    iconName: 'category',
    colorHex: '#9E9E9E',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),

  // Income
  FinanceCategory(
    id: 'cat_salary',
    name: 'Salary & Wages',
    type: CategoryType.income,
    iconName: 'account_balance_wallet',
    colorHex: '#4CAF50',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_freelance',
    name: 'Freelance & Consulting',
    type: CategoryType.income,
    iconName: 'work',
    colorHex: '#00BCD4',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_investments',
    name: 'Investments & Dividends',
    type: CategoryType.income,
    iconName: 'trending_up',
    colorHex: '#2196F3',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_gifts',
    name: 'Gifts & Allowances',
    type: CategoryType.income,
    iconName: 'card_giftcard',
    colorHex: '#E91E63',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_refunds',
    name: 'Refunds & Reimbursements',
    type: CategoryType.income,
    iconName: 'replay',
    colorHex: '#FF9800',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
  FinanceCategory(
    id: 'cat_other_income',
    name: 'Other Income',
    type: CategoryType.income,
    iconName: 'monetization_on',
    colorHex: '#8BC34A',
    isPredefined: true,
    createdAt: DateTime.utc(2026, 1, 1),
  ),
];
